version: "3.0"
services:
  frontend:
    image: swathip123/app:v2
    container_name: react
    stdin_open: true
    ports:
      - "3001:3000"

  springboot:
    image: swathip123/web:v5
    container_name: springboot
    ports:
    - "8080:8080"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
    - "27019:27017"