version: "3.9"
services:
  frontend:
    image: pavanvere/frontend:latest
    container_name: react
    stdin_open: true
    ports:
      - "3001:3000"

  springboot:
    image: pavanvere/springboot:latest
    container_name: springboot
    ports:
    - "8080:8080"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
    - "27017:27017"